export const heroes = [
  "Ác ma",
  "Ấn chú thuật sĩ",
  "Bậc thầy vũ khí",
  "Bọ cạp sa mạc",
  "Cầm nữ",
  "Chàng trai chài lưới",
  "Chúa quỷ",
  "Cô bé yếu đuối",
  "Cô con gái của thiên nhiên",
  "Cô gái dơi",
  "Cô gái Halloween",
  "Cô gái khổng lồ",
  "Cô gái lửa",
  "Con bạc",
  "Cua ẩn sĩ máy",
  "Đá quý dị nhân",
  "Đại pháp sư",
  "Đao phủ",
  "Đấu sĩ",
  "Đứa con của gió",
  "Điêu nữ",
  "Hoa muội",
  "Hoa tỉ",
  "Hỗn mang",
  "Hồn rừng",
  "Huyết nữ kiếm khách",
  "Kẻ bí ẩn",
  "Kẻ biến hình",
  "Kẻ cắt cổ",
  "Kẻ gieo rắc ác mộng",
  "Kẻ hủy diệt",
  "Kẻ kết thúc định mệnh",
  "Kẻ khát ma lực",
  "Kẻ mang mầm bệnh",
  "Kẻ ranh mãnh",
  "Kẻ săn lùng pháp sư",
  "Kẻ tham ăn",
  "Kiếm vương",
  "Kiếm sĩ thoăn thoắt",
  "King Kong",
  "Kỵ sĩ hoàng gia",
  "Kỹ sư người máy",
  "Kỹ sư vũ khí",
  "Lãng khách hư không",
  "Lính thiện xạ",
  "Lôi cận thần",
  "Lôi nữ kiếm khách",
  "Ma cà rồng",
  "Ma lực sư",
  "Ma nữ",
  "Mắt máy",
  "Môn đệ của nước",
  "Miêu nữ",
  "Mỹ nhân ngư",
  "Nàng tiên tí hon",
  "Ngựa một sừng",
  "Người báo Cheetah",
  "Người đẹp",
  "Người điện từ",
  "Người gác rừng",
  "Người máy tân tiến",
  "Người rồng",
  "Người sói",
  "Người trấn áp",
  "Người tuyết Yeti",
  "Nhà thần kinh học",
  "Nhà vũ trụ học",
  "Nhân ngư",
  "Nhẫn giả",
  "Nhện mẹ",
  "Ninja điện",
  "Nữ chiến binh ánh dương",
  "Nữ cung thủ",
  "Nữ hoàng băng",
  "Nữ mãnh tường",
  "Nữ pháp sư chuột chũi",
  "Nữ pháp sư tập sự",
  "Nữ thần hộ mệnh",
  "Nữ thần sấm sét",
  "Nữ tu sĩ ánh trăng",
  "Pháp sư lửa",
  "Phù thủy bánh kẹo",
  "Phù thủy biển",
  "Phù thủy của cái chết",
  "Phù thủy gió",
  "Phù thủy máu",
  "Phượng hoàng lửa",
  "Quái vật của người đẹp",
  "Quái vật dung nham",
  "Quốc vương",
  "Quỷ khổng lồ",
  "Quỷ lửa",
  "Rồng băng",
  "Sát thủ",
  "Siêu năng lực gia",
  "Slime nữ chúa (đỏ)",
  "Slime nữ chúa (xanh dương)",
  "Slime nữ chúa (vàng)",
  "Song thuẫn vệ binh",
  "Sứ giả của ánh sáng",
  "Tà khí",
  "Tay súng cự phách",
  "Tên điên",
  "Thần chết",
  "Thần không gian",
  "Thần thời gian",
  "Thằng hề ma quái",
  "Thánh chiến tướng",
  "Thây ma",
  "Thầy triệu hồn",
  "Thiên thần",
  "Thợ rèn",
  "Thợ săn đại dương",
  "Thợ săn quỷ",
  "Thợ săn tiền thưởng",
  "Thú săn mồi",
  "Võ sư nguyên tố",
  "Vị thần thù hận",
  "Vua sư tử",
  "Xà nữ",
  "Yêu nữ bạo dâm",
  "Yêu nữ khổ dâm",
];

export const cats = [
  "Auto",
  "Bounce",
  "Channeling",
  "Occur-on-action",
  "Occur-on-moving",
  "Occur-after-moving",
  "Occur-on-using-skill",
  "Occur-after-using-skill",
  "Occur-on-attacking",
  "Occur-after-attacking",
  "Occur-on-dealing-DMG",
  "Occur-on-receiving-DMG",
  "Occur-on-crit",
  "Occur-on-killing",
  "Occur-on-killed",
  "Occur-on-passive-proc",
  "Occur-on-dispelled",
  "Occur-on-expiring",
  "Occur-on-certain-%HP",
  "Occur-on-nth-attack",
  "Occur-on-nth-skill",
  "Occur-on-nth-DMG",
  "Occur-on-turns-start",
  "Occur-on-turns-end",
  "Occur-per-turn",
  "Occur-with-conditions",
  "Occur-when-different",
  "Occur-at-day",
  "Occur-at-night",
  "Cost-HP",
  "Deal-%maxHP-DMG",
  "Deal-%curHP-DMG",
  "Shield",
  "Elemental-shield",
  "End-on-moving/ed",
  "Summon",
  "Summon-skill",
  "Summon-passive-skill",
  "Summon-active-skill",
  "Strengthen-Attack",
  "Strengthen-Skill",
  "Push",
  "Pull",
  "Throw",
  "Dispel-self",
  "Dispel-ally",
  "Dispel-enemy",
  "Stun",
  "Root",
  "Restrain",
  "Handcuff",
  "Blind",
  "Knock-down",
  "Scare",
  "Lull",
  "Taunt",
  "Hex",
  "Reveal",
  "Hide",
  "Heal",
  "Restore-AP",
  "Restore-MP",
  "Restore-Cooldown",
  "Invisible",
  "Untouchable",
  "Protect",
  "Invulnerable",
  "Teleport",
  "Illusion",
  "Proc",
  "Non-dispellable-buff",
  "Non-dispellable-debuff",
  "Remove-EBE",
  "Remove-all-EBE",
  "Remove-Burnt",
  "Remove-Wet",
  "Remove-Cold",
  "Remove-Electrocuted",
  "Change-Stats",
  "Change-skill-Type",
  "Increase-Stats",
  "Increase-ATK",
  "Increase-SPD",
  "Increase-PWR",
  "Increase-DEF",
  "Increase-RES",
  "Increase-CritC",
  "Increase-CritDMG",
  "Increase-HP",
  "Increase-AR",
  "Increase-SR",
  "Increase-MR",
  "Increase-AE",
  "Increase-SE",
  "Increase-REF",
  "Increase-RA",
  "Increase-HA",
  "Infuse-DMG",
  "Have-drawback",
  "Increase-DMG-by-Cells-traveled",
  "Increase-DMG-by-Stacks",
  "Increase-DMG-by-Stats",
  "Increase-DMG-receive",
  "Increase-DMG-deal",
  "Increase-Range",
  "Increase-C.Range",
  "Expand-AOE",
  "Extend-duration",
  "Reduce-Stats",
  "Reduce-ATK",
  "Reduce-SPD",
  "Reduce-PWR",
  "Reduce-DEF",
  "Reduce-RES",
  "Reduce-CritC",
  "Reduce-CritDMG",
  "Reduce-HP",
  "Reduce-AR",
  "Reduce-SR",
  "Reduce-MR",
  "Reduce-AE",
  "Reduce-SE",
  "Reduce-REF",
  "Reduce-RA",
  "Reduce-HA",
  "Reduce-ACC",
  "Reduce-APcost",
  "Reduce-ManaCost",
  "Reduce-ManaLost",
  "Reduce-Cooldown",
  "Reduce-DMG-receive",
  "Reduce-DMG-deal",
  "Steal-Stats",
  "Steal-MP",
];
